### ISSUE TITLE
Cannot compile on raspberry 3 ( g++ (Raspbian 8.3.0-6+rpi1) 8.3.0 )

### ISSUE THREAD

**Issue by fdamhaut** [PascalPons/connect4#15]
I'm not a c/c++ expert so there might be something I overlooked while trying to compile it but i cannot manage to make a compile the solver.

I tried  : - using changing the flag to g++-8 but it did not made any difference.
             - running the installer multiple times but it did not make a difference either.
             - The CMakeList in a branch

Error seems to be linked to `position_t` in the solver and more. cf images
![c41](https://user-images.githubusercontent.com/36177525/67972418-f0ba6580-fc0e-11e9-9c3a-ca50916e399f.png)
![c42](https://user-images.githubusercontent.com/36177525/67972419-f0ba6580-fc0e-11e9-8911-5a31721b4457.png)
![c43](https://user-images.githubusercontent.com/36177525/67972420-f0ba6580-fc0e-11e9-920e-4d766d14e2cf.png)

**Comment by PascalPons** [comment]
Hi fdamhaut,

Your compilation error message seems to be related to the support of __int128 GCC non standard type. As described in the commented code source line 91-92, you can just replace the definition of position_t per:
`using position_t = uint64_t;`

this would limit the size of possible board to WIDTH * (HEIGHT + 1) <= 64, but the standard board 7x6 will fit.

**Comment by fdamhaut** [comment]
Thank you very much
